src/seproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('index.urls')),
    path('tractor/', include('tractor.urls')),
    path('u/', include('user.urls')),
]

src/user/urls.py
from django.urls import path

from .views import *

app_name = 'user'

urlpatterns = [
    path('register/', UserRegistrationView.as_view(), name='register'),
    path('register/lessee', UserRegistrationFormView.as_view(), name='register_lessee'),
    path('register/renter', UserRegistrationFormView.as_view(), name='register_renter'),
    path('login/', UserLoginFormView.as_view(), name='login'),
    path('<int:pk>/profile', ProfileFormView.as_view(), name='profile'),
    path('logout/', UserLogoutVIew.as_view(), name='logout'),

]

src/user/models.py
from django.contrib.auth.base_user import AbstractBaseUser
from django.contrib.auth.base_user import BaseUserManager
from django.contrib.auth.models import PermissionsMixin
from django.db import models
from django.db.models.signals import post_save
from django.utils.translation import ugettext_lazy as _

from .validators import phone_number_length_validator


class UserManager(BaseUserManager):
    use_in_migrations = True

    def _create_user(self, phone_number, password, **extra_fields):
        """
        Creates and saves a User with the given phone_number and password.
        """
        if not phone_number:
            raise ValueError('The given phone_number must be set')
        phone_number = phone_number
        user = self.model(phone_number=phone_number, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, phone_number, password=None, **extra_fields):
        extra_fields.setdefault('is_superuser', False)
        extra_fields.setdefault('is_staff', False)
        return self._create_user(phone_number, password, **extra_fields)

    def create_seller_user(self, phone_number, password=None, **extra_fields):
        extra_fields.setdefault('is_superuser', False)
        extra_fields.setdefault('is_staff', False)
        return self._create_user(phone_number, password, **extra_fields)

    def create_superuser(self, phone_number, password, **extra_fields):
        extra_fields.setdefault('is_superuser', True)
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_renter', True)

        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(phone_number, password, **extra_fields)


class User(AbstractBaseUser, PermissionsMixin):
    phone_number = models.CharField(_('phone number'),
                                    unique=True, max_length=10,
                                    validators=[phone_number_length_validator, ], )

    date_joined = models.DateTimeField(_('date joined'), auto_now_add=True)
    is_active = models.BooleanField(_('active'), default=True)
    is_staff = models.BooleanField(_('staff'), default=False)
    is_superuser = models.BooleanField(_('admin'), default=False)
    is_renter = models.BooleanField(_('Renter'), default=False)

    objects = UserManager()

    USERNAME_FIELD = 'phone_number'
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')

    def __str__(self):
        if len(str(self.phone_number)) == 3:
            return self.phone_number
        normalized_phone_number = '{} {} {}'.format(
            str(self.phone_number)[:3],
            str(self.phone_number)[3:6],
            str(self.phone_number)[6:]
        )
        return normalized_phone_number


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, verbose_name=_('user'))
    profile_pic = models.ImageField(_('Profile Picture'), upload_to="media/", null=True, blank=True)

    first_name = models.CharField(_('first name'), max_length=100)
    last_name = models.CharField(_('last name'), max_length=100)

    address = models.CharField(max_length=250, blank=True, null=True)

    class Meta:
        verbose_name = _('User Profile')
        verbose_name_plural = _('User Profiles')

    def __str__(self):
        return str(self.user)

    def full_name(self):
        full_name = '%s %s' % (self.first_name, self.last_name)
        return str(full_name.strip())

    def get_short_name(self):
        return self.first_name


def create_profile(instance, **kwargs):
    if kwargs['created']:
        UserProfile.objects.create(user=instance)


post_save.connect(receiver=create_profile, sender=User)

src/user/forms.py
from django import forms
from django.contrib.auth import authenticate
from django.contrib.auth.forms import ReadOnlyPasswordHashField

from .models import User, UserProfile
from .validators import phone_number_length_validator


# following two forms are created for Admin page's User model. DO NOT CHANGE ANYTHING 😅
class UserAdminCreationForm(forms.ModelForm):
    """A form for creating new users. Includes all the required
    fields, plus a repeated password."""
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Password confirmation', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('phone_number',)
        # widgets = {
        #     'phone_number': forms.NumberInput(
        #         attrs={'class': 'input'}
        #     ),
        # }

    def clean_password2(self):
        # Check that the two password entries match
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords don't match")
        return password2

    def save(self, commit=True):
        # Save the provided password in hashed format
        user = super(UserAdminCreationForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user


class UserAdminChangeForm(forms.ModelForm):
    """A form for updating users. Includes all the fields on
    the user, but replaces the password field with admin's
    password hash display field.
    """
    password = ReadOnlyPasswordHashField()

    class Meta:
        model = User
        fields = ('phone_number', 'password', 'is_active', 'is_superuser')

    def clean_password(self):
        # Regardless of what the user provides, return the initial value.
        # This is done here, rather than on the field, because the
        # field does not have access to the initial value
        return self.initial["password"]


class UserRegistrationForm(forms.ModelForm):

    phone_number = forms.CharField(label='Phone number', validators=[phone_number_length_validator],
                                   widget=forms.TextInput(
                                       attrs={
                                           'class': 'input',
                                           'placeholder': 'ex. 9876543210'
                                       }
                                   ))
    password = forms.CharField(label='Password', widget=forms.PasswordInput(
        attrs={
            'class': 'input',

        }
    ))
    password2 = forms.CharField(label='Confirm password', widget=forms.PasswordInput(
        attrs={
            'class': 'input',

        }
    ))

    class Meta:
        model = User

        # This will be displayed in the form
        fields = ['phone_number', 'password', 'password2', ]

        widgets = {
            'phone_number': forms.NumberInput(
                attrs={'class': '', 'placeholder': 'ex. 9876543210'}
            ),

        }

    def clean_password2(self):
        password = self.cleaned_data.get('password')
        password2 = self.cleaned_data.get('password2')

        if password != password2:
            raise forms.ValidationError('Password does not match')

        return password

    def clean_phone_number(self):
        phone_number = self.cleaned_data.get('phone_number')

        phone_number_qs = User.objects.filter(phone_number=phone_number)

        if phone_number_qs.exists():
            raise forms.ValidationError('This phone number is already been used. Please Login')

        return phone_number


class UserLoginForm(forms.Form):
    phone_number = forms.CharField(label='Phone number',
                                   validators=[phone_number_length_validator],
                                   widget=forms.TextInput(
                                       attrs={
                                           'class': 'input is-normal',
                                           'placeholder': "ex. 9876543210"
                                       }
                                   ))

    password = forms.CharField(label='Password', widget=forms.PasswordInput(
        attrs={
            'class': 'input',
        }
    ))

    def clean_phone_number(self):
        phone_number = self.cleaned_data.get('phone_number')

        phone_number_qs = User.objects.filter(phone_number=phone_number)

        if not phone_number_qs.exists():
            raise forms.ValidationError('This phone number does not exist. Create one using sign up link')

        return phone_number

    def clean(self, *args, **kwargs):
        phone_number = self.cleaned_data.get('phone_number')
        password = self.cleaned_data.get('password')

        if phone_number and password:
            user = authenticate(phone_number=phone_number, password=password)

            if not user:
                raise forms.ValidationError("Phone number or Password is Incorrect")

            if not user.is_active:
                raise forms.ValidationError("User is Banned.")

        return super(UserLoginForm, self).clean()


class ProfileForm(forms.ModelForm):
    profile_pic = forms.ImageField(required=False, widget=forms.FileInput)

    class Meta:
        model = UserProfile
        exclude = ['user']

        widgets = {
            'first_name': forms.TextInput(
                attrs={'class': 'input', 'placeholder': 'ex. John'}
            ),
            'last_name': forms.TextInput(
                attrs={'class': 'input', 'placeholder': 'ex. Snow'}
            ),
            'address': forms.Textarea(
                attrs={'class': 'textarea', 'placeholder': 'your village', 'rows': 5, 'cols': 1}
            )
        }


class ForgetPasswordForm(forms.Form):
    phone_number = forms.IntegerField(label='Phone number', widget=forms.NumberInput(
        attrs={
            'class': 'input is-normal',
            'placeholder': "ex. 9876543210"
        }
    ))

    def clean_phone_number(self):
        phone_number = self.cleaned_data.get('phone_number')

        if phone_number:
            """
            If phone number exists send the 6 digit OTP or whatever to reset the password
            """

            print('sending otp')

src/user/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import UpdateView

from .forms import UserRegistrationForm, UserLoginForm, ForgetPasswordForm, ProfileForm
from .models import UserProfile


def display_logged_in_warning(request):
    if request.user.userprofile.get_short_name():
        messages.warning(request, 'YOU ARE ALREADY LOGGED IN AS ' + request.user.userprofile.get_short_name().upper())
    else:
        messages.warning(request, 'YOU ARE ALREADY LOGGED IN')


class UserRegistrationView(View):
    template_name = 'user/registration.html'

    def get(self, request):
        if request.user.is_authenticated:
            display_logged_in_warning(request)

            return redirect('/')
        return render(request, self.template_name, {})


class UserRegistrationFormView(View):
    form_class = UserRegistrationForm
    template_name = 'user/registration_form.html'

    def get(self, request):
        current_path = str(request.path).rpartition('/')[-1]

        if request.user.is_authenticated:
            display_logged_in_warning(request)

            return redirect(reverse_lazy('index:index'))
        else:
            form = self.form_class(None)
            return render(request, self.template_name, {'form': form, 'current_path': current_path})

    def post(self, request):
        form = self.form_class(request.POST)

        if form.is_valid():
            user = form.save(commit=False)

            # clean data
            phone_number = form.cleaned_data['phone_number']
            password = form.cleaned_data['password2']

            current_path = str(self.request.path).rpartition('/')[-1]
            user.is_renter = 'renter' == current_path

            user.set_password(password)
            user.save()

            messages.info(request, 'Your account has been created.')

            # following line is for log in the user
            user = authenticate(phone_number=phone_number, password=password)

            if user is not None:
                login(request, user)
                if user.is_active:
                    return redirect('user:profile', user.pk)

        return render(request, self.template_name, {'form': form})


class UserLoginFormView(View):
    form_class = UserLoginForm
    template_name = 'user/login_form.html'

    def get(self, request):
        if request.user.is_authenticated:
            display_logged_in_warning(request)

            return redirect('/')

        form = self.form_class(None)
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = self.form_class(request.POST)

        if form.is_valid():
            phone_number = form.cleaned_data.get('phone_number')
            password = form.cleaned_data.get('password')

            user = authenticate(phone_number=phone_number, password=password)
            login(request, user)

            # displays the name of person logged in.
            if user.userprofile.first_name:
                messages.info(request, 'Welcome back, ' + str(user.userprofile.full_name()))

            else:
                messages.info(request, 'Welcome back, User')

            return redirect('/')

        return render(request, self.template_name, {'form': form})


class UserLogoutVIew(View):

    @staticmethod
    def get(request):

        # This prevent users to manually enter the logout link
        if request.user.is_authenticated:
            logout(request)
            messages.info(request, 'You are successfully logged out')

        else:
            messages.warning(request, 'No user is currently logged in!')
        return redirect('/')


class ProfileFormView(UpdateView):
    model = UserProfile
    form_class = ProfileForm
    template_name = 'user/profile_form.html'
    success_url = reverse_lazy('index:index')


class ForgetPasswordFormView(View):
    form_class = ForgetPasswordForm
    template_name = 'user/forget_password.html'

    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name, {'form': form})

src/templates/user/forget_password.html
{% extends 'index/base.html' %}

{% block title %}
    Forget Password
{% endblock %}

{% block body %}
    <div class="container level-item">
        <form method="POST" class="notification">
            {% csrf_token %}
            <fieldset>
                <legend class="title">Forget Password?</legend>
                <hr class="has-background-grey-lighter">

                <div class="field">
                    <label class="label">Phone Number</label>
                    <div class="control has-icons-left">
                        <input class="input is-success" type="text" placeholder="Text input" value="bulma">

                        <span class="icon is-small is-left">
                            <i class="fas fa-phone"></i>
                        </span>

                    </div>
                    <p class="help is-success">This username is available</p>
                </div>

            </fieldset>


        </form>
    </div>

{% endblock body %}

src/templates/user/form-template.html
{% for field in form %}
    <div>
        <div>
            <span class="has-text-danger small">{{ field.errors }}</span>
        </div>

        <label class="label">{{ field.label_tag }}</label>
        <div>{{ field }}</div>
    </div>
{% endfor %}

src/templates/user/form_template.html
{% if form.non_field_errors %}
    <ul class="has-text-danger help">
        {% for error in form.non_field_errors %}
            <li>{{ error }}</li>
        {% endfor %}
    </ul>
{% else %}
    <br>
{% endif %}

{% for hidden_field in form.hidden_fields %}
    {% if hidden_field.errors %}
        <ul class="has-text-danger help">
            {% for error in hidden_field.errors %}
                <li>(Hidden field {{ hidden_field.name }}) {{ error }}</li>
            {% endfor %}
        </ul>
    {% else %}
        <br>
    {% endif %}
    {{ hidden_field }}
{% endfor %}

{% for field in form.visible_fields %}
    <div>
        <label class="label">
            {{ field.label_tag }}

                {% if field.field.required %}
                    <span class="has-text-danger" title="Required Field">{% block required-text %}{% endblock required-text %}</span>
                {% endif %}

        </label>

        <div>{{ field }}</div>

        {% if field.errors %}
            <div>
                <span class="has-text-danger help">{{ field.errors }}</span>
                {% if field.help_text %}
                    <small class="help has-text-danger">{{ field.help_text }}</small>
                {% endif %}
            </div>
        {% else %}
            {% if field.help_text %}
                <small class="help">{{ field.help_text }}</small>
            {% endif %}
            <br>
        {% endif %}
    </div>
    <br>
{% endfor %}

src/templates/user/login_form.html
{% extends 'index/base.html' %}


{% block title %}
    Login
{% endblock title %}

{% block body %}
    <div class="container">
        <div class="level-item">
            <div class="column is-two-fifths is-mobile-full">

                <form method="POST">
                    {% csrf_token %}
                    <div class="notification is-light">

                        <fieldset>
                            <legend class='title'>Existing User? <span class="has-text-primary">Login Here.</span>
                            </legend>

                            <hr class="has-background-grey-lighter">
                            <br>
                            {% include 'index/form_template.html' %}
                        </fieldset>

                        <div class="form-group">
                            <button class="button is-primary" type="submit">Log in</button>
                        </div>

                        <br>

                        <div><a href="#" class="has-text-link">Forgot Password?</a></div>
                        <br>

                        <div>Need an account? <a class="has-text-link" href="{% url 'user:register' %}">Sign up</a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>

{% endblock body %}

src/templates/user/profile_form.html
{% extends 'index/base.html' %}

{% block title %}Profile{% endblock title %}


{% block body %}
    <div class="container">
        <div class="level-item">
            <div class="column is-two-fifths is-mobile-full">

                <form method="POST">
                    {% csrf_token %}
                    <div class="notification is-light">

                        <fieldset>
                            <legend class='has-text-centered title'>My Profile</legend>

                            <hr class="has-background-grey-lighter">
                            {% include 'index/form_template.html' %}
                        </fieldset>

                        <div class="form-group">
                            <button class="button is-primary" type="submit">Submit</button>
                        </div>

                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock body %}

src/templates/user/registration.html
{% extends 'index/base.html' %}

{% block title %}
    Register
{% endblock title %}

{% block body %}
    <div class="container is-12">
        <div class="column is-offset-1 is-10  is-mobile-full ">
            <h1 class="has-text-grey-darker has-text-centered title">New User? <span
                    class="has-text-primary">Register Here.</span></h1>
            <br><br>

            <div class="columns">

                {#LESSEE#}
                <div class="column">
                    <article class="message is-primary column is-medium ">
                        <div class='message-header'>
                            Are you a Lessee?
                        </div>
                        <div class="message-body has-text-justified">
                            Register through here, if you want to be an lessee. As a lessee you could rent other's
                            equipment
                            and
                            use them on your farm.
                        </div>
                        <br>
                        <div class="buttons is-centered">
                            <a class="button is-primary is-outlined" href="{% url 'user:register_lessee' %}"> Sign
                                Up</a>


                        </div>
                    </article>
                </div>

                {#RENTER#}
                <div class="is-offset-2 column">
                    <article class="message is-primary is-outlined column is-medium">
                        <div class='message-header '>
                            Are you a Renter?
                        </div>
                        <div class="message-body has-text-justified">
                            Register through here, if you want to be a renter. As a renter you could list your tractor
                            and
                            the
                            implements for others to rent.
                        </div>
                        <br>
                        <div class="buttons is-centered">
                            <a class="button is-primary is-outlined" href="{% url 'user:register_renter' %}"> Sign
                                Up</a>
                        </div>
                    </article>
                </div>
            </div>

            <br><br>
            <div>Already have an account? <a class="has-text-link" href="{% url 'user:login' %}">Log
                in</a></div>
        </div>
    </div>
{% endblock body %}

src/templates/user/registration_form.html
{% extends 'index/base.html' %}

{% block title %}
    Register
{% endblock title %}

{% block body %}
    <div class="container">
        <div class="level-item">
            <div class="column is-two-fifths is-mobile-full">
                <form method="POST" class="notification ">
                    {% csrf_token %}
                    <div class="notification is-light">

                        {% if form.non_field_errors %}
                            <ul>
                                {% for error in form.non_field_errors %}
                                    <li>{{ error }}</li>
                                {% endfor %}
                            </ul>
                        {% endif %}

                        {% for hidden_field in form.hidden_fields %}
                            {% if hidden_field.errors %}
                                <ul>
                                    {% for error in hidden_field.errors %}
                                        <li>(Hidden field {{ hidden_field.name }}) {{ error }}</li>
                                    {% endfor %}
                                </ul>
                            {% endif %}
                            {{ hidden_field }}
                        {% endfor %}

                        <fieldset>
                            <legend class='title'>Register as <span
                                    class="has-text-primary">{{ current_path | title }}.</span>
                            </legend>
                            <hr class="has-background-grey-lighter">
                            <br>
                            {% include 'index/form_template.html' %}

                        </fieldset>
                        <br>

                        <div class="form-group">
                            <button class="button is-primary" type="submit">Signup</button>
                        </div>

                        <br>

                        <div>Already have an account? <a class="has-text-link" href="{% url 'user:login' %}">Log
                            in</a></div>
                    </div>
                </form>
            </div>
        </div>
    </div>

{% endblock body %}