src/seproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('index.urls')),
    path('tractor/', include('tractor.urls')),
    path('u/', include('user.urls')),
]

src/tractor/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from .views import (TractorDetailView,
                    MyTractorView,
                    TractorCreateView,
                    TractorUpdateView,
                    TractorDeleteView)

app_name = 'tractor'

urlpatterns = [
    path('', MyTractorView.as_view(), name='my_tractor'),
    path('<int:pk>/', TractorDetailView.as_view(), name='detail'),
    path('add/', TractorCreateView.as_view(), name='add'),
    path('<int:pk>/update', TractorUpdateView.as_view(), name='update'),
    path('<int:pk>/delete', TractorDeleteView.as_view(), name='delete'),
    # path('checkout/', Checkout().as_view(), name='checkout'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/user/urls.py
from django.urls import path

from .views import *

app_name = 'user'

urlpatterns = [
    path('register/', UserRegistrationView.as_view(), name='register'),
    path('register/lessee', UserRegistrationFormView.as_view(), name='register_lessee'),
    path('register/renter', UserRegistrationFormView.as_view(), name='register_renter'),
    path('login/', UserLoginFormView.as_view(), name='login'),
    path('<int:pk>/profile', ProfileFormView.as_view(), name='profile'),
    path('logout/', UserLogoutVIew.as_view(), name='logout'),

]

src/tractor/models.py
from django.db import models
from django.db.models.signals import post_save
from django.urls import reverse
from django.utils.translation import ugettext_lazy as _

from user.models import User


class Implementation(models.Model):
    implement = models.CharField(max_length=50, )

    def __str__(self):
        return self.implement


class MyImplementation(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    implement = models.ManyToManyField(Implementation)

    def __str__(self):
        return self.user.phone_number


class Tractor(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    image = models.ImageField(upload_to="media/", null=True)

    TRACTOR_COMPANY_CHOICE = (
        ('John Deere', 'John Deere'),
        ('Tafe', 'Tafe'),
        ('Escorts', 'Escorts'),
        ('Swaraj', 'Swaraj'),
        ('Mahindra', 'Mahindra'),
        ('Sonalika', 'Sonalika'),
        ('Trakstar', 'Trakstar'),
        ('Kubota', 'Kubota'),
    )

    drive = models.IntegerField(_('drive'))
    hp = models.IntegerField(_('hp'))
    rent_per_hour = models.IntegerField(_('rent per hour'))
    brand_name = models.CharField(_('brand'), max_length=30, choices=TRACTOR_COMPANY_CHOICE, default='1')
    model_name = models.CharField(_('model'), max_length=30)
    note = models.TextField(_('note'), blank=True)

    def __str__(self):
        return str(self.brand_name) + ' - ' + str(self.model_name)

    def get_absolute_url(self):
        return reverse('tractor:detail', kwargs={'pk': self.pk})


def create_implementation(sender, instance, **kwargs):
    if kwargs['created'] and sender.is_renter:
        MyImplementation.objects.create(user=instance)


post_save.connect(receiver=create_implementation, sender=User)

src/tractor/forms.py
from django import forms

from .models import Tractor


class TractorCreationForm(forms.ModelForm):
    class Meta:
        model = Tractor

        exclude = [
            'user',
        ]

        widgets = {

            'drive': forms.TextInput(
                attrs={'class': 'input', 'type': 'number', }
            ),
            'hp': forms.TextInput(
                attrs={'class': 'input', 'type': 'number', }
            ),
            'rent_per_hour': forms.TextInput(
                attrs={'class': 'input', 'type': 'number', }
            ),
            'brand_name': forms.Select(
                attrs={'class': 'select', }
            ),
            'model_name': forms.TextInput(
                attrs={'class': 'input', }
            ),
            'rent_choice': forms.Select(
                attrs={'class': 'select', }
            ),
            'working_radius': forms.TextInput(
                attrs={'class': 'input', 'type': 'number', }
            ),
            'note': forms.Textarea(
                attrs={'class': 'textarea', }
            ),
        }

src/tractor/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import DetailView, ListView, CreateView, UpdateView, DeleteView

from index.decorators import renter_only
from .forms import TractorCreationForm
from .models import Tractor


# stripe.api_key = settings.STRIPE_SECRET


class TractorDetailView(DetailView):
    model = Tractor
    template_name = 'tractor/tractor_detail.html'


class MyTractorView(LoginRequiredMixin, ListView):
    model = Tractor
    template_name = 'tractor/my_tractor.html'
    context_object_name = 'tractors'

    @renter_only
    def get_queryset(self):
        return self.model.objects.filter(user=self.request.user)


class TractorCreateView(LoginRequiredMixin, CreateView):
    model = Tractor
    context_object_name = 'tractors'
    form_class = TractorCreationForm

    def form_valid(self, form):
        tractor = form.save(commit=False)

        # clean data
        tractor.user = self.request.user
        tractor.save()

        messages.success(self.request, str(tractor) + ' is added')

        return redirect('tractor:my_tractor')


class TractorUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Tractor
    form_class = TractorCreationForm
    context_object_name = 'tractors'

    def test_func(self):
        if self.request.user == self.model.user:
            return True
        return False


class TractorDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Tractor
    success_url = reverse_lazy('tractor:my_tractor')

    def test_func(self):
        if self.request.user == self.model.user:
            return True
        return False


class Checkout(LoginRequiredMixin, View):
    template_name = 'tractor/checkout.html'

src/templates/tractor/checkout.html
{% extends 'index/base.html' %}

{% block title %}
    Payment
{% endblock %}

{% block body %}
    payment here
{% endblock %}

src/templates/tractor/detail.html
{% extends 'index/base.html' %}

{% block title %}
    {{ tractor }}
{% endblock title %}

{% block body %}
    <div class="container">
        <div class="notification">
            <article class="media">
                <figure class="media-left">
                    <p class="image is-128x128">
                        <img src="{{ tractor.Image.url }}" alt="tractor image">
                    </p>
                </figure>
                <div class="media-content">
                    <div class="content">
                        <p><strong>Tractor:</strong>{{ tractor.brand_name }}</p>
                        <p><strong>Owner:</strong>{{ tractor.username }}</p>
                        <div class="columns">
                            <div class="column">
                                <strong>Drive:</strong>{{ tractor.Drive }}
                            </div>
                            <div class="column">
                                <strong>City:</strong>{{ tractor.city }}
                            </div>
                        </div>
                        <div class="columns">
                            <div class="column">
                                <strong>Hp:</strong>{{ tractor.Hp }}
                            </div>
                            <div class="column">
                                <strong>Rent Per Hour:</strong>{{ tractor.RentPerHour }}
                            </div>
                        </div>
                        <div class="columns">
                            <div class="column">
                                <strong>Mobile:</strong>{{ tractor.number }}
                            </div>
                            <div class="column">
                                <strong>Model Number:</strong>{{ tractor.model_name }}
                            </div>
                        </div>
                    </div>
                    <div class="columns">
                        <div class="column"></div>
                        <div class="column"><a href="/checkout/{{ tractor.id }}" style="text-decoration: none;">
                            <button class="button is-info {% if request.user.phone_number == tractor.user.phone_number %}title='You own this Tractor' is-disabled{% endif %}"
                                    {% if request.user.phone_number == tractor.user.phone_number %}disabled{% endif %}>
                                Send Enquiry
                            </button>
                        </a>
                        </div>
                    </div>
                </div>
            </article>
        </div>
    </div>

{% endblock %}

src/templates/tractor/my_tractor.html
{% extends 'index/base.html' %}

{% block title %}
    kh-e-ti
{% endblock %}

{% block body %}
    <div class="container">
        <div class="title has-text-centered">My Tractors</div>
        <a href="{% url 'tractor:add' %}" class="button is-rounded is-primary is-pulled-right"><i
                class="far fa-plus"></i>&nbsp;Add</a>
        <br><br>
        {% if tractors %}
            {% include 'tractor/tractor_list.html' %}
        {% else %}
            <h2 class="has-text-grey-darker has-text-centered">You have no Tractors. <a href="{% url 'tractor:add' %}"
                                                                                        class="is-info">create one</a>.
            </h2>
        {% endif %}
    </div>
{% endblock %}

src/templates/tractor/tractor_confirm_delete.html
{% extends 'index/base.html' %}

{% block title %}Delete Tractor confirm{% endblock title %}


{% block body %}
    <div class="container">
        <br><br>
        <div class="message is-danger">
            <form method="POST">
                {% csrf_token %}
                <h1 class=" message-header">Delete tractor {{ tractor }}?</h1>
                <div class="message-body">
                    <p>Are you sure that you want to delete your tractor {{ tractor }}?</p>
                    <p>This step is irreversible. Think wisely.</p>
                </div>


                <br><br>
                <div class="columns">
                    <div class="column"></div>
                    <div class="column has-text-right" style="margin-right:15px;">
                        <button type="submit" class="button is-danger is-outlined">Confirm</button>
                        <a href="{% url 'tractor:my_tractor' %}" class="button is-info">Go back</a>
                    </div>
                </div>
            </form>

        </div>
    </div>
{% endblock %}

src/templates/tractor/tractor_detail.html
{% extends 'index/base.html' %}

{% block title %}
    {{ tractor }}
{% endblock title %}

{% block body %}
    <div class="container">
        <div class="notification">
            <article class="media">
                <figure class="media-left">
                    <p class="image is-128x128">
                        <img src="{{ tractor.image.url }}" alt="tractor image">
                    </p>
                </figure>
                <div class="media-content">
                    <div class="content">
                        <p><strong>Tractor: </strong>{{ tractor.brand_name }}</p>
                        <p><strong>Owner: </strong>{{ tractor.user.userprofile.full_name }}</p>

                        <div class="columns">
                            <div class="column">
                                <strong>Drive: </strong>{{ tractor.drive }}
                            </div>
                        </div>

                        <div class="columns">
                            <div class="column">
                                <strong>Hp: </strong>{{ tractor.hp }}
                            </div>
                            <div class="column">
                                <strong>Rent Per Hour: </strong>{{ tractor.rent_per_hour }}
                            </div>
                        </div>

                        <div class="columns">
                            <div class="column">
                                <strong>Mobile: </strong>{{ tractor.user.phone_number }}
                            </div>

                            <div class="column">
                                <strong>Model Number: </strong>{{ tractor.model_name }}
                            </div>
                        </div>
                    </div>
                    <div class="columns">
                        <div class="column"></div>
                        {# this is done to create an empty row #}

                        <div class="column">
                            {% if tractor.user == request.user %}
                                <div class="field is-grouped">
                                    <p class="control">
                                        <a class="button is-info" href="{% url 'tractor:update' tractor.pk %}">
                                            <i class="fal fa-edit">&nbsp;&nbsp;</i>Update
                                        </a>
                                    </p>

                                    <p class="control">
                                        <a class="button is-danger" href="{% url 'tractor:delete' tractor.pk %}">
                                            <i class="fal fa-trash-alt">&nbsp;&nbsp;</i>Delete
                                        </a>
                                    </p>
                                </div>

                            {% else %}
                                <a href="#" class="button is-info">
                                    Rent
                                </a>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </article>
        </div>

        <div class="notification">
            <p><strong>Implements available: </strong>
                <br>
                {% for implement in tractor.user.myimplementation.implement.all %}
                    <ul style="list-style: none">
                        <li>{{ implement }}</li>
                    </ul>
                {% endfor %}

        </div>
    </div>

{% endblock %}

src/templates/tractor/tractor_form.html
{% extends 'index/base.html' %}

{% block title %}
    New Tractor
{% endblock title %}

{% block body %}
    <div class="container">
        <div class="level-item">
            <div class="column is-two-fifths is-mobile-full">

                <form method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="notification is-light">

                        <fieldset>
                            <legend class='title has-text-centered'>Add new Tractor.
                            </legend>

                            <hr class="has-background-grey-lighter">
                            <br>


                            {% include 'index/form_template.html' %}
                        </fieldset>

                        <div class="form-group">
                            <button class="button is-primary" type="submit">Add</button>
                        </div>

                    </div>
                </form>
            </div>
        </div>
    </div>

{% endblock body %}

src/templates/tractor/tractor_list.html
<section class="container">
    {% for tractor in tractors %}
        <div class="notification container">
            <article class="media">
                <figure class="media-left">
                    <p class="image is-128x128">
                        <img src="{{ tractor.image.url }}" alt="tractor image: {{ tractor }}">
                    </p>
                </figure>
                <div class="media-content">
                    <div class="content">
                        <p><strong>Tractor: </strong>{{ tractor.brand_name }}</p>
                        {% if tractor.user.full_name %}
                            <p><strong>Owner: </strong>{{ tractor.user.full_name }}</p>
                        {% endif %}

                        <div class="columns">
                            <div class="column">
                                <strong>Drive: </strong>{{ tractor.drive }}
                            </div>
                            <div class="column">
                                <strong>Model: </strong>{{ tractor.model_name }}
                            </div>
                        </div>
                        <div class="columns">
                            <div class="column">
                                <strong>Hp: </strong>{{ tractor.hp }}
                            </div>
                            <div class="column">
                                <strong>Rent Per Hour: </strong>{{ tractor.rent_per_hour }}
                            </div>
                        </div>
                    </div>
                    <div class="columns">
                        <div class="column"></div>
                        <div class="column"><a href="{% url 'tractor:detail' tractor.id %}" class="button is-primary">Details</a>
                        </div>
                    </div>
                </div>
            </article>
        </div>
    {% endfor %}
</section>