src/index/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from .views import IndexView, rent_view, search_view, signin_view

app_name = 'index'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('rent/', rent_view, name='rent'),
    path('hire/', search_view, name='hire'),
    path('signin/', signin_view, name='signIn')
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/seproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('index.urls')),
    path('tractor/', include('tractor.urls')),
    path('u/', include('user.urls')),
]

src/tractor/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from .views import (TractorDetailView,
                    MyTractorView,
                    TractorCreateView,
                    TractorUpdateView,
                    TractorDeleteView)

app_name = 'tractor'

urlpatterns = [
    path('', MyTractorView.as_view(), name='my_tractor'),
    path('<int:pk>/', TractorDetailView.as_view(), name='detail'),
    path('add/', TractorCreateView.as_view(), name='add'),
    path('<int:pk>/update', TractorUpdateView.as_view(), name='update'),
    path('<int:pk>/delete', TractorDeleteView.as_view(), name='delete'),
    # path('checkout/', Checkout().as_view(), name='checkout'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/user/urls.py
from django.urls import path

from .views import *

app_name = 'user'

urlpatterns = [
    path('register/', UserRegistrationView.as_view(), name='register'),
    path('register/lessee', UserRegistrationFormView.as_view(), name='register_lessee'),
    path('register/renter', UserRegistrationFormView.as_view(), name='register_renter'),
    path('login/', UserLoginFormView.as_view(), name='login'),
    path('<int:pk>/profile', ProfileFormView.as_view(), name='profile'),
    path('logout/', UserLogoutVIew.as_view(), name='logout'),

]

src/templates/index/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <link rel="stylesheet" href="{% static 'bulma-0.7.4/css/bulma.css' %}">
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.7.2/css/all.css">
    <link rel="stylesheet" href="{% static 'index.css' %}">

    <link rel="icon" type="image/ico" href="{% static 'favicon.ico' %}">

    <script src="https://code.jquery.com/jquery-3.3.1.js"></script>

    {% block head %}
    {% endblock %}

    <title>
        {% block title %}
        {% endblock %} | KH-e-TI
    </title>
</head>

<body>
<!-- NAVBAR -->
<nav class="navbar" role="navigation" aria-label="main navigation">
    <div class="navbar-brand">
        <a class="navbar-item has-text-primary" href='{% url 'index:index' %}'>
            <strong><i class="fas fa-tractor"></i> KH-e-TI</strong>
        </a>

        <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false"
           data-target="navbarBasicExample">
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
        </a>
    </div>

    <div id="navbarBasicExample" class="navbar-menu">
        <div class="navbar-start">
            <a class="navbar-item">
                Buy
            </a>

            <div class="navbar-item has-dropdown is-hoverable">
                <a class="navbar-link">
                    More
                </a>

                <div class="navbar-dropdown">
                    <a class="navbar-item">
                        Rent
                    </a>
                    <a class="navbar-item">
                        Hire
                    </a>
                    <a class="navbar-item">
                        Schemes
                    </a>
                    <hr class="navbar-divider">
                    <a class="navbar-item">
                        About
                    </a>

                </div>
            </div>


        </div>

        {% if user.is_authenticated %}
            <div class="navbar-end">
            {% if user.is_renter %}
                <a class="navbar-item" href="{% url 'tractor:my_tractor' %}" style="margin-right:5px;">
                    <i style="margin-right:5px;" class="fas fa-tractor"></i>My Tractors
                </a>
            {% endif %}
            <div class="navbar-item has-dropdown is-hoverable">
                <a class="navbar-link is-arrowless" href="{% url 'user:profile' user.pk %}">
                    <i class="fas fa-user is-small" style="margin-right:5px;"> </i>
                    <span class="is-capitalized">
                            {% if request.user.userprofile.full_name %}
                                {{ request.user.userprofile.full_name }}
                            {% else %}
                                {{ request.user }}
                            {% endif %}
                    </span>
                </a>

                <div class="navbar-dropdown">
                    <a class="navbar-item" href="{% url 'user:logout' %}">
                        <i class="fas fa-sign-out-alt is-large" style="margin-right:5px;"> </i> Logout
                    </a>
                </div>
            </div>
        {% else %}

            <div class="navbar-item">
                <div class="buttons">
                    <a class="button is-primary" href="{% url 'user:register' %}">
                        <strong>Sign up</strong>
                    </a>
                    <a class="button is-light" href="{% url 'user:login' %}">
                        Log in
                    </a>
                </div>
            </div>
        {% endif %}
        </div>

    </div>

</nav>
{% if messages %}
    {% for message in messages %}
        {% if message.tags == 'success' %}
            <article class="message is-success is-small">
                <div class="message-body">{{ message }}</div>
            </article>
        {% elif message.tags == 'error' %}
            <article class="message is-danger is-small">
                <div class="message-body">{{ message }}</div>
            </article>
        {% elif message.tags == 'warning' %}
            <article class="message is-warning is-small">
                <div class="message-body has-text-warning"><i class="icon far fa-triangle"></i> {{ message }}</div>
            </article>
        {% elif message.tags == 'info' %}
            <article class="message is-info is-small">
                <div class="message-body">{{ message }}</div>
            </article>
        {% endif %}
    {% endfor %}
{% endif %}
{% block body %}
{% endblock %}
</body>

<script>
    $(document).ready(function () {

        // Check for click events on the navbar burger icon
        $(".navbar-burger").click(function () {

            // Toggle the "is-active" class on both the "navbar-burger" and the "navbar-menu"
            $(".navbar-burger").toggleClass("is-active");
            $(".navbar-menu").toggleClass("is-active");

        });
    });
</script>

</html>

src/templates/index/form_template.html
{% if form.non_field_errors %}
    <ul class="has-text-danger help">
        {% for error in form.non_field_errors %}
            <li>{{ error }}</li>
        {% endfor %}
    </ul>
{% else %}
    <br>
{% endif %}

{% for hidden_field in form.hidden_fields %}
    {% if hidden_field.errors %}
        <ul class="has-text-danger help">
            {% for error in hidden_field.errors %}
                <li>(Hidden field {{ hidden_field.name }}) {{ error }}</li>
            {% endfor %}
        </ul>
    {% else %}
        <br>
    {% endif %}
    {{ hidden_field }}
{% endfor %}

{% for field in form.visible_fields %}
    <div>
        <label class="label">
            {{ field.label_tag }}

            {% if field.field.required %}
                <span class="has-text-danger"
                      title="Required Field">{% block required-text %}{% endblock required-text %}</span>
            {% endif %}

        </label>

        <div>{{ field }}</div>

        {% if field.errors %}
            <div>
                <span class="has-text-danger help">{{ field.errors }}</span>
                {% if field.help_text %}
                    <small class="help has-text-danger">{{ field.help_text }}</small>
                {% endif %}
            </div>
        {% else %}
            {% if field.help_text %}
                <small class="help">{{ field.help_text }}</small>
            {% endif %}
            <br>
        {% endif %}
    </div>
    <br>
{% endfor %}

src/templates/index/index.html
<!-- Includes Base.html -->
{% extends 'index/base.html' %}

<!-- Title -->
{% block title %}
    kh-e-ti
{% endblock %}

<!-- Body -->
{% block body %}
    <section class="hero is-medium is-primary">
        <div class="hero-body">
            <div class="container">
                <h1 class="title">
                    <i class="fas fa-tractor"></i> KH-e-TI
                </h1>
                <h2 class="subtitle">
                    We make your life better.<br/>
                </h2>
            </div>
        </div>
    </section>

    {% include 'tractor/tractor_list.html' %}
{% endblock %}